### ISSUE TITLE
Historical reference point lines on biomass plots

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/iscam-gui#12]
See screen capture from mseR where user enters the year range. I just remembered how the min and max buttons work. If the user picks min, then the Bmin is the minimum over that year range. Same for max, i.e., USR is max over the year range. For mean, USR or Bmin is the average over that year range. 

For MCMC, you calculate USR and Bmin for each sample using the approaches above then calculate the median for plotting.

NOTE these are the agreed years to use for 5AB and 5CD:
5CD:
Bmin is biomass in 1971, so you can use a year range of 1970-1971 (or 1971-1971).
USR is average biomass between 1956 and 2004.

There was no consensus for 5AB so maybe just use the same ones for now.
We haven’t discussed 3CD, so same again maybe.

**Comment by cgrandin** [comment]
Done in commit 2c5de34279bd1a4826e48f42e678ac44d08b58d7

**Comment by robynforrest** [comment]
These are great Chris. Please could they be dashed lines with red for Bmin and green for Bmax. Please could Bmax be called USR. Thanks!
