### ISSUE TITLE
plotIndexMPD (radio button Index fits) is not working

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/iscam-gui#3]
function **plotIndexMPD** in iscam-gui-figures-timeseries.r is not working for herring (2 surveys).

$indices looks like this:
[[1]]
       iyr      it gear area group sex wt timing
 [1,] 1951  66.143    4    1     1   0  1      1
 [2,] 1952  72.376    4    1     1   0  1      1
 [3,] 1953 111.307    4    1     1   0  1      1
...
[36,] 1986  41.575    4    1     1   0  1      1
[37,] 1987  41.737    4    1     1   0  1      1

[[2]]
       iyr      it gear area group sex     wt timing
 [1,] 1988  24.976    5    1     1   0 1.1666      1
 [2,] 1989  66.052    5    1     1   0 1.1666      1
 [3,] 1990  67.150    5    1     1   0 1.1666      1
...
[28,] 2015 104.481    5    1     1   0 1.1666      1
[29,] 2016 129.502    5    1     1   0 1.1666      1

**Comment by cgrandin** [comment]
It works, you just have to supply the index number as 4 or 5 for the 2 surveys. iscam-gui gets this information from the ABUNDANCE INDICES - A RAGGED ARRAY: (1,nit,1,nit_nobs,1,5) section of the data file.

On the GUI there is a little box in the bottom section where you can increment/decrement the index to plot. The default is 1 so it will give you the error:
iscam-gui->plotIndexMPD: That gear does not have an index in the model.

**Comment by jaclyncleary** [comment]
thx Chris.
Can I request an option where both indices appear on the same figure, with a breakpoint between survey types?

**Comment by jaclyncleary** [comment]
also- plotting error bars (cv) on the survey index:
In the herring survey index there are no annual cv's. This is because the index is not extrapolated over survey areas as occurs with a trawl survey. There is a weight for each survey year in the dat file, which gives higher weight to the recent survey (index 5) over the older one (index 4). 
Can I request an option where the cv's can be included/ excluded from the plot? In my case they are large, not informative, and make it hard to see the model fits to the index.

**Comment by cgrandin** [comment]
Sure, I'll have a look tomorrow maybe - trying to get the document structure stuff working for Matt as well.

**Comment by jaclyncleary** [comment]
no problem, definitely work on the document with Matt as priority.

**Comment by jaclyncleary** [comment]
I commented out the cv's in the plot. Closing this issue.
