### ISSUE TITLE
iscam-gui not working with *mcmc.csv files

### ISSUE THREAD

**Issue by jaclyncleary** [cgrandin/iscam-gui#5]
error- "file" has no mcmc output data associated with it

Chris- we need to start "viewing" the mcmc outputs (model diagnostics, trace plots, posteriors/ priors). These exist under "DiagnosticFigs" in iscam-gui but they don't work with the updated format of *mcmc.csv files.  We have two options:  (1) start viewing outputs using csas-latex -perhaps it's easy (?) to create a pdf for each stock/ scenario (x10) with key figures? OR (2) ask you to fix the iscam-gui and we use iscam-gui to view model diagnostics until Herring_LaTex template is working and populated with figures and tables. Please advise :)

**Comment by cgrandin** [comment]
I haven't had the time to change iscam-gui to fit the herring directory structure. The plots work for me when I copy the directories in from one stock, i.e. you can't have doubly-nested directories in iscam-gui yet. Will this work for the time being?

**Comment by jaclyncleary** [comment]
I got it working- I didn't realize the mcmc's needed to be in a mcmc folder, e.g.,
Scenarios/6A_V2_AM1_2016estvalsphzON_timevaryingM/mcmc
